# Further options in the toucan module

CONFIG_ZMK_KEYBOARD_NAME="akiowehK2"
CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

CONFIG_ZMK_TRACKPAD=y
CONFIG_ZMK_TRACKPAD_FINGERS=5
# TPS43 factory axes 2048 x 1792, rotated by switch-xy.
CONFIG_ZMK_TRACKPAD_LOGICAL_X=1792
CONFIG_ZMK_TRACKPAD_LOGICAL_Y=2048
